version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: riwi_postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-bd_antonio_pulgarin_hamilton}
      POSTGRES_USER: ${POSTGRES_USER:-app_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-12345678}
      TZ: UTC
    ports:
      - "${POSTGRES_PORT:-5434}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-app_user} -d ${POSTGRES_DB:-bd_antonio_pulgarin_hamilton}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
